name: "Continuous Delivery Workflow"

on:
  push:
    branches:
     - "master"
    workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Fetch Origin
        run: git fetch origin master
        shell: powershell

      - name: Diff Tree Against Previous Commit
        run: $modifiedFiles = (git diff-tree --no-commit-id --name-only -r ${{ github.ref }} ${{ github.ref }}~1); $modifiedFiles;